# Generated by Django 3.0.6 on 2020-06-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='School',
            field=models.CharField(choices=[('1', '电子信息与工程学院'), ('2', '材料科学与工程学院'), ('3', '机电工程学院'), ('4', '化学工程学院'), ('5', '经济管理学院'), ('6', '天体物理学院'), ('7', '数理学院'), ('8', '文法学院'), ('9', '生命科学与技术学院'), ('10', '继续教育学院'), ('11', '马克思主义学院'), ('12', '国际教育学院'), ('13', '交通学院'), ('14', '中德学院')], default='信息技术与科学学院', max_length=30),
        ),
    ]
